# Generated by Django 5.2.7 on 2025-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_slug_alter_label_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
