name: SonarCloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv and sync
        run: |
          pip install uv
          uv sync --frozen
          uv pip install pytest pytest-cov pytest-django

      - name: Run tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: task_manager.settings
          SECRET_KEY: test-secret-key
          DEBUG: "False"
          DATABASE_URL: sqlite:///./test.sqlite3
          ALLOWED_HOSTS: testserver,localhost,127.0.0.1
          SECURE_SSL_REDIRECT: "False"
          SESSION_COOKIE_SECURE: "False"
          CSRF_COOKIE_SECURE: "False"
        run: |
          mkdir -p reports
          uv run pytest --ds=task_manager.settings \
                        --cov=task_manager \
                        --cov-report=xml \
                        --junitxml=reports/junit.xml
          sed -i 's|<source>/home/runner/work/python-project-52/python-project-52</source>|<source>.</source>|g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}