name: SonarCloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужно для анализа pull request'ов

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # если в requirements.txt нет pytest-cov, добавь:
          # pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: task_manager.settings
        run: |
          pytest \
            --ds=task_manager.settings \
            --cov=task_manager \
            --cov-report=xml:coverage.xml \
            --junitxml=reports/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
